---
title       : Air Quality
subtitle    : New York City, Year 1973
author      : Anubhav Sood
job         : Data Analyst
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Dataset

The 'Air Quality' dataset consists of four parameters (Ozone, Solar Radiation, Wind and Temperature) which are used to determine the air quality of New York city for the month of May-September in the year 1973.<br/><br/>
The data were obtained from the New York State Department of Conservation (ozone data) and the National Weather Service (meteorological data).

--- .class #id 

## Parameters explained

1. *Ozone* – Mean ozone in parts per billion from 1300 to 1500 hours at Roosevelt Island.
2. *Solar.R* - Solar radiation in Langleys in the frequency band 4000–7700 Angstroms from 0800 to 1200 hours at Central Park.
3. *Wind* - Average wind speed in miles per hour at 0700 and 1000 hours at LaGuardia Airport.
4. *Temp* - Maximum daily temperature in degrees Fahrenheit at La Guardia Airport.

--- .class #id 

## Process

1. Step 1: Select the ‘Air Quality’ variable one wants to assess e.g. wind, temperature etc.
2. Step 2: Select the time period (month) for which the assessment needs to be done e.g. May
3. Step 3: Click on submit button
4. Step 4: The output is displayed on the screen

## Output

The output sheet is in the form of a bar chart which displays the required information.<br/>
X-axis: displays the days of the month from Day 1 to Day 31.<br/>
Y-axis: The chosen variable data points e.g. if wind variable is selected then it displays the ‘miles per hour’ on the given axis, following are the data points for all variables.<br/>

--- .class #id 

## Slide 2




